### ISSUE TITLE
Make AbstractDifferentiation Compatible

### ISSUE THREAD

**Issue by dynamic-queries** [SciML/FluxNeuralOperators.jl#118]
@yuehhua Do you see any major refactoring to make OperatorKernel AD compatible in general ?

**Comment by yuehhua** [comment]
Currently, NeuralOperators use Zygote as AD backend, the same as Flux. IMO, NeuralOperators should already compatible with [AbstractDifferentiation](https://github.com/JuliaDiff/AbstractDifferentiation.jl) since Zygote is compatible with AbstractDifferentiation. Anything I missed?

**Comment by dynamic-queries** [comment]
I think, differentiating OperatorKernel with ForwardDiff.jl is not possible.

**Comment by yuehhua** [comment]
If you want supporting forward mode differentiation, just define `frule` for `OperatorKernel`. It would just work.

**Comment by dynamic-queries** [comment]
I see.
