### ISSUE TITLE
DoublePendulum example not working

### ISSUE THREAD

**Issue by jcvillaquira** [SciML/FluxNeuralOperators.jl#125]
Currently some of the examples are not working. For example, in the DoublePendulum I get 

`julia> using DoublePendulum; DoublePendulum.train()
[ Info: Training on CPU
ERROR: BoundsError: attempt to access 3×30×64×100 Array{ComplexF32, 4} at index [1:4, 1:16, 1:64, 1:100]`
[full stacktrace](https://github.com/SciML/NeuralOperators.jl/files/11165292/stacktrace.txt)

and a similar error in the Navier-Stokes example. The Burgers example is working.

**Comment by HanjiangHu** [comment]
Hi @jcvillaquira , I meet the same issue with the DoublePendulum example, could you please share me the way to fix it?

**Comment by jcvillaquira** [comment]
@HanjiangHu choose a smaller number of modes. This happens because the number of channels is too small for the modes.

**Comment by HanjiangHu** [comment]
Thanks for the quick response, yes, it works after I change the number of modes to smaller ones. Thank you once again for your help!
