### ISSUE TITLE
Documentation landing page is a mess

### ISSUE THREAD

**Issue by ablaom** [SciML/FluxNeuralOperators.jl#149]
The issue is pretty obvious (and makes it pretty hard to make sense of the page): https://docs.sciml.ai/NeuralOperators/stable/

Somewhere a code block hasn't been fenced properly, or something...

**Comment by ChrisRackauckas** [comment]
Oh no. @ArnoStrouwen could you take a look at this today?

**Comment by ArnoStrouwen** [comment]
dev looks fine: https://docs.sciml.ai/NeuralOperators/dev/.
Try releasing?

**Comment by ArnoStrouwen** [comment]
Stable looks fine to me.
