### ISSUE TITLE
about FNO

### ISSUE THREAD

**Issue by BNUhex** [SciML/FluxNeuralOperators.jl#152]
**Question❓**
If I use FNO to build a nn model ,what will my data look like?In other word ,what will be size(data) and what's the meaning of it?Could use rand to creat data to show me?
If you need help or have a general question, the primary online discussion venue for Julia is the [Discourse forum](https://discourse.julialang.org/).
Here, we only answer questions about internal design and implementation.

**Comment by ChrisRackauckas** [comment]
It's just like every other Flux layer: it would output layer_size x batch size where the batch size is determined by the input. I suggest checking out the Flux documentation to start.
