### ISSUE TITLE
Can't install NeuralOperators in Julia 1.10.2

### ISSUE THREAD

**Issue by Andrew-Milestone** [SciML/FluxNeuralOperators.jl#159]
Hello,

is it possible that the package cannot be installed in Julia 1.10.2? I have already made posts about this in [github-julia](https://github.com/JuliaLang/julia/issues/54292) and in [julialang.org](https://discourse.julialang.org/t/how-to-install-neuraloperators-as-a-cpu-version/113283) and this has also been confirmed in [github-julia](https://github.com/JuliaLang/julia/issues/54292). A detail bug-description and an example can be found in the mentioned links. A short info would be helpful.

Thanks in advance and best regards,

Andreas

**Comment by ChrisRackauckas** [comment]
It installed just fine on latest, https://github.com/SciML/NeuralOperators.jl/pull/162 so maybe try v1.10.3? Make sure you're using a standard binary from https://julialang.org/downloads/
