### ISSUE TITLE
Separate out spectral transforms from operators for easy switching

### ISSUE THREAD

**Issue by bischtob** [SciML/FluxNeuralOperators.jl#40]
It would be great for flexibility if we could separate out conceptually and in code the spectral transforms from the operators. This would allow swapping of transforms (wavelets, spherical harmonics, Fourier, etc.) and it may allow also mix-and-match type transforms (e.g., spherical harmonic + legendre in the vertical).

An example of how this could be done can be found here: https://github.com/CliMA/OperatorFlux.jl/tree/main/src

**Comment by yuehhua** [comment]
An abstract type on top of `SpectralConv` type would work. Maybe `AbstractTransform`? Since the transformation here should be a kernel and the layer forms a integral transform operation.

Generaliztion for `FourierOperator` layer is also needed to support more neural operators for different types of kernel transforms.

**Comment by foldfelis** [comment]
@yuehhua, So in your idea we will get various kind of `XxxConv` type under `AbstractTransform`, is that correct?

**Comment by foldfelis** [comment]
Here, I would like to make several changes. 

1. In `OperatorFlux.jl` there is a `transform` field, I'll probably go with that way and extend the `SpectralConv`.
2. The name of `FourierOperator` layer in `NeuralOperators.jl` is ambiguous. Since the whole model is regarded as a "operator". I'll change that to some other name.

**Comment by yuehhua** [comment]
> In OperatorFlux.jl there is a `transform` field, I'll probably go with that way and extend the `SpectralConv`.

It should be the same way here. Your idea is to parametrize out `transform` field and let it be interchangeable with other `xxxConv` under abstract type `AbstractTransform`. It is simple to make `AbstractTransform` type as an interface that we could define a series of functions for different `xxxConv` type. For example, a transformation requires a forward transform `forward` method and an inverse transform `inverse` method. For different `xxxConv` types, they should have their own implementations., e.g. `forward(::FourierTransform, x)`. So, I think the design here in OperatorFlux.jl gives a pretty good model to follow on and it is easy to add new transformation and easy to read, which fits open-closed principle and readability well in software engineering.

> The name of `FourierOperator` layer in NeuralOperators.jl is ambiguous. Since the whole model is regarded as a "operator". I'll change that to some other name.

This idea agrees with mine! We should abstract out a parametric type `NeuralOperator` from `FourierOperator`. I would like it to be some what like `NeuralOperator{FourierTransform}`.

**Comment by foldfelis** [comment]
> It should be the same way here. Your idea is to parametrize out `transform` field and let it be interchangeable with other `xxxConv` under abstract type `AbstractTransform`. It is simple to make `AbstractTransform` type as an interface that we could define a series of functions for different `xxxConv` type. For example, a transformation requires a forward transform `forward` method and an inverse transform `inverse` method. For different `xxxConv` types, they should have their own implementations., e.g. `forward(::FourierTransform, x)`. So, I think the design here in OperatorFlux.jl gives a pretty good model to follow on and it is easy to add new transformation and easy to read, which fits open-closed principle and readability well in software engineering.

I totally agree with that.

> This idea agrees with mine! We should abstract out a parametric type NeuralOperator from FourierOperator. I would like it to be some what like NeuralOperator{FourierTransform}.

Here, suppose you mean the [`FourierOperator`](https://github.com/SciML/NeuralOperators.jl/blob/1ec89bf1faede27cbaadc456030bb63cb533d281/src/fourier.jl#L98) in `NeuralOperators.jl`. And no, this is not an "operator" but just a layer.

**Comment by foldfelis** [comment]
Summary:

- Change the name `FourierOperator` to `OperatorKernel`
- Implement transform family under abstract type `AbstractTransform`
- Extend `OperatorKernel` to `OperatorKernel{<:AbstractTransform}`
- Implement `SpectralConv` function as a constructor of `OperatorKernel{FourierTransform}`

**Comment by yuehhua** [comment]
> this is not an "operator" but just a layer.

Here, I feel like something weird. In its meaning, it is still an operator. It learns a function mapping from a function space to another function space but just we implement it as a layer. I think that's why we call it *neural* operator, which makes a metaphor to user "this operator is implemented in the form of a neural network layer".

**Comment by foldfelis** [comment]
> Here, I feel like something weird. In its meaning, it is still an operator. It learns a function mapping from a function space to another function space but just we implement it as a layer. I think that's why we call it _neural_ operator, which makes a metaphor to user "this operator is implemented in the form of a neural network layer".

Maybe @zongyi-li also have a different way of looking at it?

**Comment by yuehhua** [comment]
I can provide another example. Neural ODE and neural PDE are another metaphor to hint user that they learn a continuous ODE/PDE function in the form of a neural network layer. In neural ODE, the ODE part is defined by the problem setting and the key is to learn a continuous function over a neural network layer. Thus, a ODE solver is used to provide a solution of continuous function for neural network layer.
