### ISSUE TITLE
Add the temporal bundling and pushforward trick in the FlowOverCircle example 

### ISSUE THREAD

**Issue by YichengDWu** [SciML/FluxNeuralOperators.jl#42]
In [this paper](https://arxiv.org/abs/2202.03376), the authors claim that " Temporal bundling and the pushforward trick improve FNO dramatically". It would be nice to see if this trick could be added to this library.

**Comment by yuehhua** [comment]
It seems that the pushforward trick here is equivalent to forward AD. It is effective that if we cut a temporal bunding and know the final time point to train with. Forward AD could do it very well. However, this paper seems requiring message-passing network from GNN, which will be provided as Graph Neural Operator in the future.

**Comment by YichengDWu** [comment]
> It seems that the pushforward trick here is equivalent to forward AD. It is effective that if we cut a temporal bunding and know the final time point to train with. Forward AD could do it very well. However, this paper seems requiring message-passing network from GNN, which will be provided as Graph Neural Operator in the future.

We can look into it when their code is released. A more pressing matter is to implement the variation of the FNO used in section 5.3. The original code is [here](https://github.com/zongyi-li/fourier_neural_operator/blob/master/FNO-torch.1.6/fourier_2d_time.py).

**Comment by YichengDWu** [comment]
Also, I am wondering how you plan to implement the Graph Neural Operator, with `GeometricFlux.jl`?

**Comment by yuehhua** [comment]
> Also, I am wondering how you plan to implement the Graph Neural Operator, with `GeometricFlux.jl`?

Yes, I am the maintainer of GeometricFlux.jl, where already have message-passing network.

**Comment by YichengDWu** [comment]
> > Also, I am wondering how you plan to implement the Graph Neural Operator, with `GeometricFlux.jl`?
> 
> Yes, I am the maintainer of GeometricFlux.jl, where already have message-passing network.

Cool. How is the package's performance compared to [DGL](https://github.com/dmlc/dgl)? I know people there have done loads of optimizations.

**Comment by YichengDWu** [comment]
> > It seems that the pushforward trick here is equivalent to forward AD. It is effective that if we cut a temporal bunding and know the final time point to train with. Forward AD could do it very well. However, this paper seems requiring message-passing network from GNN, which will be provided as Graph Neural Operator in the future.
> 
> We can look into it when their code is released. A more pressing matter is to implement the variation of the FNO used in section 5.3. The original code is [here](https://github.com/zongyi-li/fourier_neural_operator/blob/master/FNO-torch.1.6/fourier_2d_time.py).

The variation is already in the [example](https://github.com/SciML/NeuralOperators.jl/tree/master/example/FlowOverCircle). The pushforward trick should be applied there

**Comment by yuehhua** [comment]
Yeah, but I have no idea how to use pushforward trick here. It needs forward AD support while Flux.jl doesn't support forward AD by default. Maybe we should wait for the code and see how they implement it.

**Comment by YichengDWu** [comment]
I don't see why the forward-mode AD is used. It looks like it should be equivalent to adding noise at each iteration. Could you refer to where the forward-mode AD is used in the paper?

**Comment by yuehhua** [comment]
Pushforward trick itself is forward-mode AD here. In its abstract, it claim that
> In this work, we build a solver, satisfying these proper-
ties, where all the components are based on neural message passing, replacing
all heuristically designed components in the computation graph with backprop-
optimized neural function approximators.

It seems that they use forward mode AD in replacement of reverse mode AD, which is backpropagation for deep learning.

**Comment by yuehhua** [comment]
Sorry, I was misleaded by the figures. Pushforward trick here is not forward AD. In the forward AD, they use the same term "pushforward" 😂

**Comment by YichengDWu** [comment]
I see. Forward-mode AD is sometimes referred to as "pushforward". But this term refers to something else in this paper.

Their code is not released yet. I will stay tuned and work on the implemetation.

**Comment by YichengDWu** [comment]
I have implemented both of them but I don't see a major improvement in performance. It's better to close this issue now.
