### ISSUE TITLE
Notebooks are broken

### ISSUE THREAD

**Issue by AnasAbdelR** [SciML/FluxNeuralOperators.jl#47]
I tried running the super resolution example notebook and it errors with:
```julia


SystemError: opening file "/Desktop/dev/NeuralOperators.jl/example/SuperResolution/src/../model/model.jld2": No such file or directory
```

It appears that the ```model.jld2``` file is actually missing from the repo? This looks like a problem that occurs across all the notebooks.

**Comment by foldfelis** [comment]
Hi, You need to train the model first. Change directory into the `example/SuperResolution` and run 

```sh
$ julia --proj
```

And press `]` to enter the pkg mode and run `up` under pkg mode to update deps.

After that, you can train the model by:

```julia
julia> using SuperResolution; SuperResolution.train()
```

**Comment by foldfelis** [comment]
The notebook can be found [here](https://neuraloperators.sciml.ai/dev/assets/notebook/super_resolution_mno.jl.html). Sorry for the broken link. I'll fix that ASAP.
