### ISSUE TITLE
Compare `FluxTraining` and `Flux.train!`

### ISSUE THREAD

**Issue by foldfelis** [SciML/FluxNeuralOperators.jl#61]
For FlowOverCircle example:

[FluxTraining](https://github.com/SciML/NeuralOperators.jl/blob/bm_ft/example/FlowOverCircle/src/FlowOverCircle.jl): 1165.640799 seconds (296.68 M allocations: 39.971 GiB, 7.36% gc time, 3.42% compilation time)
[Flux.train!](https://github.com/SciML/NeuralOperators.jl/blob/bm_f/example/FlowOverCircle/src/FlowOverCircle.jl): 1119.503231 seconds (289.83 M allocations: 18.220 GiB, 6.30% gc time, 3.73% compilation time)

**Comment by foldfelis** [comment]
c.c. @chengchingwen

**Comment by yuehhua** [comment]
They have quite similar performance, but FluxTraining has more memory allocations. However, performance might not be the first place for choosing a good the training framework. The richness of functionality should be more important than that. The support of epoch, early stop, learning rate scheduling or model auto-saving etc, could provide more value to users and developers.
