### ISSUE TITLE
Move data part from examples to MLDatasets.jl

### ISSUE THREAD

**Issue by yuehhua** [SciML/FluxNeuralOperators.jl#62]
It is more systematic to move datasets from examples to [MLDatasets.jl](https://github.com/JuliaML/MLDatasets.jl). It is not good for examples to host their own datasets. This way example can be simplified into just a pure script.

**Comment by foldfelis** [comment]
This is currently not necessary. It is more importent for user to understand what is going on in the preprocess and getter method fot the data. And the examples are not that complcated in the current situation as well.
