### ISSUE TITLE
graph neural operator

### ISSUE THREAD

**Issue by YichengDWu** [SciML/FluxNeuralOperators.jl#74]
The implemented graph neural operator
<img width="464" alt="image" src="https://user-images.githubusercontent.com/38997672/176096868-e8f2c743-0b05-4157-a38a-d517a86e142e.png">
 is not the same one in the original paper
<img width="502" alt="image" src="https://user-images.githubusercontent.com/38997672/176096839-a4df23e8-553b-496c-854f-78fe34e9ce6c.png">

Is this intentional?

**Comment by yuehhua** [comment]
You can check the equation again. In paper, it defines

$$
e(x,y) = [v_t(x), v_t(y)]
$$

**Comment by YichengDWu** [comment]
I only see 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/38997672/176334579-09b306fa-7fc3-45a6-9ed4-c9605ccd92d4.png">
in the paper [Neural Operator: Graph Kernel Network for Partial Differential Equations](https://arxiv.org/abs/2003.03485). Which one are you refering to?

**Comment by yuehhua** [comment]
I was supposed to think of $a(x)$ as node feature, and it lacks the coordinates here.

**Comment by YichengDWu** [comment]
$a(x)$ is not the trainable node embeddings but the nontrainable input function. If you are learning the operator from the initial condition to the solution at $t$, then $a(x)=u(0,x)$

**Comment by yuehhua** [comment]
Good! It can be fixed.

**Comment by YichengDWu** [comment]
Also note the output of the net is reshaped to be a matrix. It is in fact the [NNConv](https://docs.dgl.ai/generated/dgl.nn.pytorch.conv.NNConv.html?highlight=nnconv#dgl.nn.pytorch.conv.NNConv) as mentioned in the paper

**Comment by yuehhua** [comment]
Oh! I also missed this point.

**Comment by yuehhua** [comment]
@MilkshakeForReal You can check it if it is right.

**Comment by YichengDWu** [comment]
It looks good.
